import type {
  Transaction,
  Fund,
  MonthlySnapshot,
  MerchantRule,
  PaperTradeScenario,
} from '@/types';
import { getCurrentYearMonth } from './finance/calculations';

function getOffsetMonth(offset: number): string {
  const d = new Date();
  d.setMonth(d.getMonth() + offset);
  return getCurrentYearMonth(d);
}

const currentMonth = getCurrentYearMonth();
const lastMonth = getOffsetMonth(-1);
const twoMonthsAgo = getOffsetMonth(-2);

export const DEMO_FUNDS: Fund[] = [
  {
    id: 'fund-living',
    name: 'Quỹ sinh hoạt & Nhà cửa',
    monthlyAllocation: 8000000,
    categoryMappings: ['Hóa đơn', 'Nhà cửa'],
    merchantMappings: ['điện', 'nước', 'internet', 'chung cư'],
    createdAt: new Date().toISOString(),
    active: true,
  },
  {
    id: 'fund-dining',
    name: 'Quỹ ăn uống',
    monthlyAllocation: 4500000,
    categoryMappings: ['Ăn uống'],
    merchantMappings: ['highland', 'starbucks', 'phở', 'cơm', 'cafe'],
    createdAt: new Date().toISOString(),
    active: true,
  },
  {
    id: 'fund-transport',
    name: 'Quỹ di chuyển',
    monthlyAllocation: 1500000,
    categoryMappings: ['Di chuyển'],
    merchantMappings: ['grab', 'be', 'xăng', 'petrolimex'],
    createdAt: new Date().toISOString(),
    active: true,
  },
  {
    id: 'fund-learning',
    name: 'Quỹ học tập & Phát triển',
    monthlyAllocation: 2000000,
    categoryMappings: ['Giáo dục'],
    merchantMappings: ['coursera', 'udemy', 'sách'],
    createdAt: new Date().toISOString(),
    active: true,
  },
  {
    id: 'fund-emergency',
    name: 'Quỹ dự phòng khẩn cấp',
    monthlyAllocation: 3000000,
    categoryMappings: ['Sức khỏe', 'Đầu tư'],
    merchantMappings: [],
    createdAt: new Date().toISOString(),
    active: true,
  },
];

export const DEMO_MERCHANT_RULES: MerchantRule[] = [
  {
    id: 'rule-grab',
    pattern: 'grab',
    category: 'Di chuyển',
    fundId: 'fund-transport',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rule-highland',
    pattern: 'highland',
    category: 'Ăn uống',
    fundId: 'fund-dining',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rule-shopee',
    pattern: 'shopee',
    category: 'Mua sắm',
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-demo-1',
    source: 'EMAIL',
    sourceMessageId: 'msg_vcb_salary_curr',
    sourceProvider: 'gmail',
    bank: 'Vietcombank',
    accountHint: '8899',
    direction: 'IN',
    amount: 25000000,
    currency: 'VND',
    occurredAt: `${currentMonth}-05T09:00:00.000Z`,
    description: 'Chuyển khoản tiền lương',
    counterparty: 'Công ty Cổ phần Công nghệ',
    category: 'Lương',
    status: 'POSTED',
    parserConfidence: 0.95,
    rawSubject: 'VCB: TK 8899| GD: +25,000,000 VND',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tx-demo-2',
    source: 'EMAIL',
    sourceMessageId: 'msg_vcb_cafe_curr',
    sourceProvider: 'gmail',
    bank: 'Vietcombank',
    accountHint: '8899',
    direction: 'OUT',
    amount: 145000,
    currency: 'VND',
    occurredAt: `${currentMonth}-06T14:30:00.000Z`,
    description: 'Thanh toán Highland Coffee',
    counterparty: 'Highland Coffee',
    category: 'Ăn uống',
    fundId: 'fund-dining',
    status: 'POSTED',
    parserConfidence: 0.9,
    rawSubject: 'VCB: TK 8899| GD: -145,000 VND',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tx-demo-3',
    source: 'EMAIL',
    sourceMessageId: 'msg_vcb_grab_curr',
    sourceProvider: 'gmail',
    bank: 'Vietcombank',
    accountHint: '8899',
    direction: 'OUT',
    amount: 280000,
    currency: 'VND',
    occurredAt: `${currentMonth}-08T08:15:00.000Z`,
    description: 'Thanh toán Grab Car di chuyển',
    counterparty: 'Grab Vietnam',
    category: 'Di chuyển',
    fundId: 'fund-transport',
    status: 'POSTED',
    parserConfidence: 0.9,
    rawSubject: 'VCB: TK 8899| GD: -280,000 VND',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tx-demo-4',
    source: 'MANUAL',
    direction: 'OUT',
    amount: 6500000,
    currency: 'VND',
    occurredAt: `${currentMonth}-10T10:00:00.000Z`,
    description: 'Tiền thuê căn hộ tháng này',
    counterparty: 'Chủ nhà',
    category: 'Nhà cửa',
    fundId: 'fund-living',
    status: 'POSTED',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tx-demo-5',
    source: 'EMAIL',
    sourceMessageId: 'msg_unknown_curr',
    sourceProvider: 'gmail',
    bank: 'Unknown',
    direction: 'OUT',
    amount: 500000,
    currency: 'VND',
    occurredAt: `${currentMonth}-12T16:00:00.000Z`,
    description: 'Giao dịch trực tuyến cổng thanh toán',
    category: 'Khác',
    status: 'NEEDS_REVIEW',
    parserConfidence: 0.5,
    rawSubject: 'Xác nhận giao dịch thanh toán',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_MONTHLY_SNAPSHOTS: MonthlySnapshot[] = [
  {
    month: twoMonthsAgo,
    totalIncome: 24000000,
    totalExpense: 17500000,
    netSavings: 6500000,
    fundResults: [
      { fundId: 'fund-living', fundName: 'Quỹ sinh hoạt & Nhà cửa', allocated: 8000000, spent: 7800000, remaining: 200000 },
      { fundId: 'fund-dining', fundName: 'Quỹ ăn uống', allocated: 4500000, spent: 4200000, remaining: 300000 },
      { fundId: 'fund-transport', fundName: 'Quỹ di chuyển', allocated: 1500000, spent: 1400000, remaining: 100000 },
      { fundId: 'fund-learning', fundName: 'Quỹ học tập & Phát triển', allocated: 2000000, spent: 1500000, remaining: 500000 },
      { fundId: 'fund-emergency', fundName: 'Quỹ dự phòng khẩn cấp', allocated: 3000000, spent: 0, remaining: 3000000 },
    ],
    closedAt: new Date().toISOString(),
  },
  {
    month: lastMonth,
    totalIncome: 25000000,
    totalExpense: 18200000,
    netSavings: 6800000,
    fundResults: [
      { fundId: 'fund-living', fundName: 'Quỹ sinh hoạt & Nhà cửa', allocated: 8000000, spent: 8100000, remaining: -100000 },
      { fundId: 'fund-dining', fundName: 'Quỹ ăn uống', allocated: 4500000, spent: 4600000, remaining: -100000 },
      { fundId: 'fund-transport', fundName: 'Quỹ di chuyển', allocated: 1500000, spent: 1300000, remaining: 200000 },
      { fundId: 'fund-learning', fundName: 'Quỹ học tập & Phát triển', allocated: 2000000, spent: 1800000, remaining: 200000 },
      { fundId: 'fund-emergency', fundName: 'Quỹ dự phòng khẩn cấp', allocated: 3000000, spent: 0, remaining: 3000000 },
    ],
    closedAt: new Date().toISOString(),
  },
];

export const DEMO_PAPER_TRADES: PaperTradeScenario[] = [
  {
    id: 'trade-demo-1',
    instrument: 'BTC',
    direction: 'LONG',
    entryPrice: 63500,
    currentPrice: 65200,
    margin: 1000,
    leverage: 5,
    stopLoss: 60000,
    takeProfit: 70000,
    feePercent: 0.05,
    createdAt: new Date().toISOString(),
    status: 'PROFIT',
  },
];
